### ISSUE TITLE
I recive clone message after disconnect and reconnect

### ISSUE THREAD

**Issue by llorcasantana** [godsharp/GodSharp.Socket#10]
Hello. I have some problem here, I see your example and tested your code (Its great but the way) My problem is, Im using winform client, so when the first start send a message to server its fine, console server showme the message. Then, when i closed server and open again to do the same operation, the server show me duplicate message recived. How can I fix the problem? 

Also if you provide a guide it will would great. Im learning socket and your code is the best for me.

Im using the lasted nuget at the moment. Thanks

**Comment by seayxu** [comment]
can you show the code?

**Comment by llorcasantana** [comment]
[Client.zip](https://github.com/godsharp/GodSharp.Socket/files/5226539/Client.zip)
[Server.zip](https://github.com/godsharp/GodSharp.Socket/files/5226540/Server.zip)

The client is a class and the server is a command line like your example code

**Comment by llorcasantana** [comment]
I think is like as the client take a new socket identity on reconnect but keep the last identity and send to server over two sockets connections. Also if I close the server and re open again, it send 3 messages. 

Thanks for your atention

**Comment by seayxu** [comment]
you should invoke `Stop` method when new TcpClient before.

**Comment by llorcasantana** [comment]
So, Will put stop method in onReconect and call server start? How I should put this code? Sorry my ignorance

**Comment by seayxu** [comment]
two way:
- disabled reconnect in current code
- enabled reconnect but must to call `Stop` method when new instance before.

**Comment by llorcasantana** [comment]
Thanks. It work!!
