### ISSUE TITLE
how can the server send message to client ?

### ISSUE THREAD

**Issue by wx409790282** [godsharp/GodSharp.Socket#3]
as you mentioned , the server can only  answer the client's request. what should i do if i want send message from server to client positivly，or brocast to a list of client ?
thank you

**Comment by seayxu** [comment]
you can get a `TcpSender` object with specified `host` and `port`.
code is [here](https://github.com/godsharp/GodSharp.Socket/blob/master/src/GodSharp.Socket/Tcp/Server/SocketServer.cs#L334).

sample code:
```
SocketServer server;
TcpSender sender = server["host",port];
sender.Send("message");
```

**Comment by wx409790282** [comment]
thank you very much. i read your sample and know how to do it after post this topic.
