### ISSUE TITLE
what will happened if a client end it's connection and reconnect 

### ISSUE THREAD

**Issue by wx409790282** [godsharp/GodSharp.Socket#4]
Thank you for another question.
What will happened if a client end it's connection to server, and reconnect several seconds later?
In my code,client can connect to server successfully, function like client.Connect() ,client.Start() work well, 
 send("hei") can get an return of 3.  
While in Server, OnConnected event will not trigger again, and the Number of server.client is 0, and it can not get hei from client. also can not do anything with client.
what is the wrong with me , thank you .

**Comment by wx409790282** [comment]
here is my client 
`client = new SocketClient(Server, Port);
            client.OnData = (sender, data) =>
            {
                //get server data
                string message = client.Encoding.GetString(data, 0, data.Length);
                record(message+ "\r\n");
                record(mh.handle(message)+"\r\n");
            };
            client.OnClosed = (sender) =>
             {
                 record("连接关闭了");
                 client.Connect();
             };
            //client.OnConnected = (sender) =>
            //{

            //};
            mh = new MessageHandler(client);
            client.Connect();
            client.Start();`

**Comment by wx409790282** [comment]
here is my server:
`server = new SocketServer(port: 12580)
            {
                OnConnected = (sender) =>
                {
                    record($"Client {sender.RemoteEndPoint.ToString()} connected");
                    band_listview2();
                }

            };

            server.OnData = (sender, data) =>
            {
                //get client data
                string message = server.Encoding.GetString(data, 0, data.Length);
                record($"server received data from {sender.RemoteEndPoint}: {message}");
            };

            server.Listen();
            server.Start();`

**Comment by wx409790282** [comment]
nothing special from your sample.
thank you for help

**Comment by seayxu** [comment]
can you show your complete code to redisplay your question?

**Comment by wx409790282** [comment]
[AutoUpdating.zip](https://github.com/godsharp/GodSharp.Socket/files/1977795/AutoUpdating.zip)
here it is.
it contains two project, server and client. start the server and client, it can communicate successful. start  client without server, it throw an exception . but close client after starting two project, it makes me confuse. client run normally but can't send or receive   message with server. 
thanks

**Comment by wx409790282** [comment]
forget to say that, but when i close server , the client can show that connection was stopped.

**Comment by seayxu** [comment]
@wx409790282 you should update version to lasted, current version is `1.0.2-preview5`.

**Comment by seayxu** [comment]
@wx409790282 点击链接加入群聊【GodSharp交流群】：https://jq.qq.com/?_wv=1027&k=5wx6qEU

**Comment by wx409790282** [comment]
Thank you , i choose a stable version of 1.0.1.
it sloved
