### ISSUE TITLE
TCP Sample crash when the client connect to a non-open server

### ISSUE THREAD

**Issue by LarryMai** [godsharp/GodSharp.Socket#7]
Hi Seayxu, 

    I encounter an error when  try to use TCPClientSample to connect my tcp server, but I don't start my server yet.  So the sample will show connecction failed. 
   But, I see the sample go crash !!! 
   
   I enter break point debugging, see it crash in TcpConnection:;ConnectCallback
![image](https://user-images.githubusercontent.com/3214309/51510038-64387680-1e36-11e9-9a3c-7c0f196de285.png)

    The exception is not really be handled, 
    (Originally, I think will be handled at TcpConnection::Start . )
    I suggest you code should add OnException callback for the exception
           catch (SocketException ex)
            {            
                OnException?.Invoke(new NetClientEventArgs<ITcpConnection>(this) {  Exception = ex});
            }
            catch (Exception ex)
            {
                OnException?.Invoke(new NetClientEventArgs<ITcpConnection>(this) { Exception =ex});
            }
      or maybe you have better consideration for it. anyway.

Best Regards

**Comment by seayxu** [comment]
Thanks.
I fixed, you can catch exception when calling the `Start` method.
If no problem then close this issue.

**Comment by LarryMai** [comment]
okay
